### ISSUE TITLE
Location update is not working.

### ISSUE THREAD

**Issue by ambujshukla-cdn** [crowdconnected/colocator-ios-swift-3.2#1]
Hi,
I have integrated the location update for background mode but it is not showing location icon as mentioned in the doc.
I have taken these steps:-
#import <CCLocation/CCLocation.h>
@property (nonatomic, strong) CCLocation *ccLocationObj;
 self.ccLocationObj = [CCLocation sharedInstance];
    [self.ccLocationObj startWithURLString:@"key.colocator.net:443/socket" apiKey:@"key"];

```
<key>UIBackgroundModes</key>
	<array>
		<string>location</string>
	</array>
```

```
<key>NSLocationAlwaysUsageDescription</key>
	<string>App wants to access your location.</string>
```

But the location is not tracked on the testing account. Please have a look and suggest me what I'm doing wrong.

**Comment by kernchen** [comment]
Hi @ambujshukla-cdn, will get back to you asap.

**Comment by ambujshukla-cdn** [comment]
Hi Ralf,
Thanks for the update.. But this issue is working fine for some networks and for some it not. So can you suggest me that is there anything to whitelist in the firewall. As the library is working for sending location.

**Comment by kernchen** [comment]
Hi @ambujshukla-cdn, sorry for delay in reply. Are you experiencing any issues, when just using the cellular network or is this related to wireless LAN? Cellular would be the main way of testing I think, since that is what most of the end-users would experience. I can also check with the team, if they had any issues previously with this. Please note, it can also be a factor on how the configuration of your API key is setup on the platform.

**Comment by kernchen** [comment]
Looking at your configuration of the background services as well, that seems correct to me.

**Comment by ghost** [comment]
Hi @ambujshukla-cdn If port 443 is blocked on your network then the library will not work

**Comment by ambujshukla-cdn** [comment]
Hi Ralf,
Thanks so much for the update. I'll check this.

**Comment by kernchen** [comment]
Seems that has been resolved, closing the issue.
